name: Build docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  image_name: godaddy_ddns

jobs:
  build_main_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: setup docker context for buildx
        id: buildx-context
        run: |
          docker context create builders || :
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build local copy
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfiles
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.image_name }}